export const USER_REQUEST_START = 'USER_REQUEST_START';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAIL = 'USER_REQUEST_FAIL';

export const POST_REQUEST_START = 'POST_REQUEST_START';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_FAIL = 'POST_REQUEST_FAIL';

export const ADD_POST_REQUEST_START = 'ADD_POST_REQUEST_START';
export const ADD_POST_REQUEST_SUCCESS = 'ADD_POST_REQUEST_SUCCESS';
export const ADD_POST_REQUEST_FAIL = 'ADD_POST_REQUEST_FAIL';

export const ALBUM_REQUEST_START = 'ALBUM_REQUEST_START';
export const ALBUM_REQUEST_SUCCESS = 'ALBUM_REQUEST_SUCCESS';
export const ALBUM_REQUEST_FAIL = 'ALBUM_REQUEST_FAIL';

export const PHOTO_REQUEST_START =  'PHOTO_REQUEST_START';
export const PHOTO_REQUEST_SUCCESS = 'PHOTO_REQUEST_SUCCESS';
export const PHOTO_REQUEST_FAIL = 'PHOTO_REQUEST_FAIL';